from typing import Literal
from langchain_core.messages import SystemMessage
from langchain_groq import ChatGroq
from dotenv import load_dotenv
load_dotenv()

# Import your state schema
from src.Agent.state import AgentState

from src.tools.get_order_status import get_order_status
from src.tools.search_policy import search_policy
from src.tools.check_return import check_return
from src.tools.initiate_return import initiate_return
from src.tools.escalate_to_human import escalate_to_human

tools = [
    get_order_status,
    search_policy,
    check_return,
    initiate_return,
    escalate_to_human,
]

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0) 
llm_with_tools = llm.bind_tools(tools)


SYSTEM_PROMPT = """You are the Trendly customer support assistant.
Your goal is to help users with order status, policy questions, and returns.

CRITICAL RULES:
1. Only answer policy questions using content returned by the `search_policy` tool. Never use outside knowledge.
2. If the policy doc doesn't cover something, say so and use the `escalate_to_human` tool — don't guess.
3. Never reveal or reference another customer's order. Before looking up or discussing any order, you must
   verify the customer's email against that order. If the conversation state already shows a verified email,
   do NOT ask for it again — reuse it.
4. Never invent discounts, exceptions, or refund amounts not stated in the policy.
5. Do not manually calculate return eligibility windows. Always use `check_return`.
6. Never ask the customer for information they have already provided earlier in this conversation
   (order ID, email, SKU, etc.). Check the conversation history before asking for anything.
"""


def chatbot_node(state: AgentState):
    """The main LLM reasoning node."""
    messages = state["messages"]

    # Prepend the system prompt dynamically if it isn't already in the message history
    if not messages or not isinstance(messages[0], SystemMessage):
        messages = [SystemMessage(content=SYSTEM_PROMPT)] + messages

    # Surface any already-verified identity so the model doesn't have to re-derive
    # it from raw chat history — and won't re-ask for it.
    verified_email = state.get("verified_email")
    if verified_email:
        messages = messages + [
            SystemMessage(
                content=f"Note: the current customer's email has already been "
                f"verified as {verified_email}. Do not ask for it again."
            )
        ]

    # Generate the model's response (which may include a tool call)
    response = llm_with_tools.invoke(messages)

    # Return the response to be appended to the state
    return {"messages": [response]}


def route_tools(state: AgentState) -> Literal["tools", "__end__"]:
    """Conditional edge logic to route to tools or end the cycle."""
    # Look at the very last message generated by the chatbot_node
    last_message = state["messages"][-1]

    # If Ollama decided to call a tool, route to the "tools" node
    if last_message.tool_calls:
        return "tools"

    # Otherwise, Ollama generated a standard text reply, so end the loop
    return "__end__"